#include <jni.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/shm.h>

#define SHMSZ     27
#define ftokpath	("/tmp")


JNIEXPORT jint JNICALL Java_javaPackage_ShmClient_shmget
(JNIEnv * env, jobject jobj, jint pid) {

	int shmid;

	/*key_t key=ftok(ftokpath,pid);
	if ( key == (key_t)-1 )
	{
		printf("error in shmget : ftok failed\n");
		return (-1);
	}*/
	
	key_t key = 5678;
	
	if ((shmid = shmget(key, SHMSZ, 0666)) < 0) {
        printf("shmget error");
        return (-1);
    }

	return (shmid);
}

// Attach a memory segment using the shmid generated by the shmget
// returns the pointer of the segment.
JNIEXPORT jstring JNICALL Java_javaPackage_ShmClient_shmat 
(JNIEnv * env, jobject jobj, jint shmid) {

char *shm="DEFAULT";

jstring result;
result = (*env)->NewStringUTF(env,shm); 

 if ((shm = shmat(shmid, NULL, 0)) == (char *) -1) {
        perror("shmat");
        return (result);
    }

	//intptr_t ret=(intptr_t)shm;
	//shmAddress = ret;
	//return (ret);
	
	result = (*env)->NewStringUTF(env,shm); 
 	return result;      
	
}
